// File generated from our OpenAPI spec by Stainless.

package me.elborai.api.models

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class MessageBatchResultsBetaResponseTest {

    @Test
    fun createMessageBatchResultsBetaResponse() {
        val messageBatchResultsBetaResponse =
            MessageBatchResultsBetaResponse.builder()
                .customId("my-custom-id-1")
                .betaSucceededResult(
                    MessageBatchResultsBetaResponse.Result.BetaSucceededResult.Message.builder()
                        .id("msg_013Zva2CMHLNnXjNJJKqJ2EF")
                        .addContent(
                            MessageBatchResultsBetaResponse.Result.BetaSucceededResult.Message
                                .Content
                                .BetaResponseTextBlock
                                .builder()
                                .addCitation(
                                    MessageBatchResultsBetaResponse.Result.BetaSucceededResult
                                        .Message
                                        .Content
                                        .BetaResponseTextBlock
                                        .Citation
                                        .BetaResponseCharLocationCitation
                                        .builder()
                                        .citedText("cited_text")
                                        .documentIndex(0L)
                                        .documentTitle("document_title")
                                        .endCharIndex(0L)
                                        .startCharIndex(0L)
                                        .type(
                                            MessageBatchResultsBetaResponse.Result
                                                .BetaSucceededResult
                                                .Message
                                                .Content
                                                .BetaResponseTextBlock
                                                .Citation
                                                .BetaResponseCharLocationCitation
                                                .Type
                                                .CHAR_LOCATION
                                        )
                                        .build()
                                )
                                .text("Hi! My name is Claude.")
                                .type(
                                    MessageBatchResultsBetaResponse.Result.BetaSucceededResult
                                        .Message
                                        .Content
                                        .BetaResponseTextBlock
                                        .Type
                                        .TEXT
                                )
                                .build()
                        )
                        .model("claude-3-7-sonnet-20250219")
                        .role(
                            MessageBatchResultsBetaResponse.Result.BetaSucceededResult.Message.Role
                                .ASSISTANT
                        )
                        .stopReason(
                            MessageBatchResultsBetaResponse.Result.BetaSucceededResult.Message
                                .StopReason
                                .END_TURN
                        )
                        .stopSequence(null)
                        .type(
                            MessageBatchResultsBetaResponse.Result.BetaSucceededResult.Message.Type
                                .MESSAGE
                        )
                        .usage(
                            MessageBatchResultsBetaResponse.Result.BetaSucceededResult.Message.Usage
                                .builder()
                                .cacheCreationInputTokens(2051L)
                                .cacheReadInputTokens(2051L)
                                .inputTokens(2095L)
                                .outputTokens(503L)
                                .build()
                        )
                        .build()
                )
                .build()
        assertThat(messageBatchResultsBetaResponse).isNotNull
        assertThat(messageBatchResultsBetaResponse.customId()).isEqualTo("my-custom-id-1")
        assertThat(messageBatchResultsBetaResponse.result())
            .isEqualTo(
                MessageBatchResultsBetaResponse.Result.ofBetaSucceeded(
                    MessageBatchResultsBetaResponse.Result.BetaSucceededResult.builder()
                        .message(
                            MessageBatchResultsBetaResponse.Result.BetaSucceededResult.Message
                                .builder()
                                .id("msg_013Zva2CMHLNnXjNJJKqJ2EF")
                                .addContent(
                                    MessageBatchResultsBetaResponse.Result.BetaSucceededResult
                                        .Message
                                        .Content
                                        .BetaResponseTextBlock
                                        .builder()
                                        .addCitation(
                                            MessageBatchResultsBetaResponse.Result
                                                .BetaSucceededResult
                                                .Message
                                                .Content
                                                .BetaResponseTextBlock
                                                .Citation
                                                .BetaResponseCharLocationCitation
                                                .builder()
                                                .citedText("cited_text")
                                                .documentIndex(0L)
                                                .documentTitle("document_title")
                                                .endCharIndex(0L)
                                                .startCharIndex(0L)
                                                .type(
                                                    MessageBatchResultsBetaResponse.Result
                                                        .BetaSucceededResult
                                                        .Message
                                                        .Content
                                                        .BetaResponseTextBlock
                                                        .Citation
                                                        .BetaResponseCharLocationCitation
                                                        .Type
                                                        .CHAR_LOCATION
                                                )
                                                .build()
                                        )
                                        .text("Hi! My name is Claude.")
                                        .type(
                                            MessageBatchResultsBetaResponse.Result
                                                .BetaSucceededResult
                                                .Message
                                                .Content
                                                .BetaResponseTextBlock
                                                .Type
                                                .TEXT
                                        )
                                        .build()
                                )
                                .model("claude-3-7-sonnet-20250219")
                                .role(
                                    MessageBatchResultsBetaResponse.Result.BetaSucceededResult
                                        .Message
                                        .Role
                                        .ASSISTANT
                                )
                                .stopReason(
                                    MessageBatchResultsBetaResponse.Result.BetaSucceededResult
                                        .Message
                                        .StopReason
                                        .END_TURN
                                )
                                .stopSequence(null)
                                .type(
                                    MessageBatchResultsBetaResponse.Result.BetaSucceededResult
                                        .Message
                                        .Type
                                        .MESSAGE
                                )
                                .usage(
                                    MessageBatchResultsBetaResponse.Result.BetaSucceededResult
                                        .Message
                                        .Usage
                                        .builder()
                                        .cacheCreationInputTokens(2051L)
                                        .cacheReadInputTokens(2051L)
                                        .inputTokens(2095L)
                                        .outputTokens(503L)
                                        .build()
                                )
                                .build()
                        )
                        .type(
                            MessageBatchResultsBetaResponse.Result.BetaSucceededResult.Type
                                .SUCCEEDED
                        )
                        .build()
                )
            )
    }
}
